### ISSUE TITLE
View image

### ISSUE THREAD

**Issue by successrequiresKnowledge** [krishpranav/Backdoorcreator#1]
![image](https://user-images.githubusercontent.com/71161018/93008789-91bbc180-f53e-11ea-9192-812725fe8202.png)

**Comment by krishpranav** [comment]
Can you please send your email id i will send you some stuffs about teaching you

**Comment by successrequiresKnowledge** [comment]
mrgray148

**Comment by krishpranav** [comment]
is this your gmail  
mrgray148@gmail.com
???

**Comment by successrequiresKnowledge** [comment]
> is this your gmail  
> 
> mrgray148@gmail.com
> 
> ???

Yes it is

**Comment by krishpranav** [comment]
ok i will send you the stuffs you want ok

**Comment by krishpranav** [comment]
i will send on 16 wed

**Comment by krishpranav** [comment]
my gmail id is: krisna.pranav@gmail.com

**Comment by krishpranav** [comment]
hey hi i have sended you email 
you just check it out if you didn't recive the email means check on your spam 
thank you

**Comment by krishpranav** [comment]
[
![Screen Shot 2020-09-16 at 8 03 04 AM](https://user-images.githubusercontent.com/68631244/93285687-1f273c00-f7f3-11ea-9483-1c1449a89047.png)
](url)

**Comment by krishpranav** [comment]
mail sent

**Comment by krishpranav** [comment]
pls send another email contains answers for the question i have sended you
